add vhost partly works

diff --git a/scripts/http_add_vhost b/scripts/http_add_vhost
--- a/scripts/http_add_vhost
+++ b/scripts/http_add_vhost
@@ -3,12 +3,13 @@ vhost=$(echo $1 | cut -d'.' -f1)
 echo $vhost
 domain=$(echo $1 | cut -d'.' -f2-)
 echo $domain
-if ["$domain" == "lennert-verwimp.sb.uclllabs.be"];
+if [ "$domain" == "lennert-verwimp.sb.uclllabs.be" ];
 	then
-	if ![["vhost" =~ [^a-zA-Z0-9]+ ]];
+	if ! [[ "$vhost" =~ [^a-zA-Z0-9]+ ]];
 	then mkdir -p /var/www/$vhost/public_html
 	touch /etc/apache2/sites-available/$vhost.conf
-	echo "<VirtualHost *:80>
+	echo 
+	"<VirtualHost *:80>
 	    ServerName $vhost.lennert-verwimp.sb.uclllabs.be
             ServerAdmin root@lennert-verwimp
             DocumentRoot /var/www/$vhost.lennert-verwimp.sb.uclllabs.be
@@ -21,22 +22,23 @@ if ["$domain" == "lennert-verwimp.sb.uclllabs.be"];
             php_value error_log /var/www/$vhost/php.error.log
 	</VirtualHost>" >> /etc/apache2/sites-available/$vhost.conf
 
-touch /var/www/$vhost/public_html/index.html
-	echo "<html>
-	<head>
-	<title>Vhost $vhost</title>
-	</head>
-	<body>
-	<p>welcome $vhost</p>
-	</body>
-	</html> >> /var/www/$vhost/public_html/index.html
+	touch /var/www/$vhost/public_html/index.html
+		echo 
+		"<html>
+		<head>
+		<title>Vhost $vhost</title>
+		</head>
+		<body>
+		<p>welcome $vhost</p>
+		</body>
+		</html>" >> /var/www/$vhost/public_html/index.html
 
-dns_add_record -t A $vhost 193.191.177.134 $domain
-a2ensite $vhost.conf
-systemctl reload apache2
+	dns_add_record -t A $vhost 193.191.177.217 $domain
+	a2ensite $vhost.conf
+	systemctl reload apache2
+	else
+	echo "invalid vhost name"
+	fi
 else
-echo "invalid vhost name"
-fi
-else
-echo "invalid domain
+echo "invalid domain"
 fi
